"""Reproducible binary fixture generator for the Phase 2 ingest test suite.

Run this script to (re-)generate all binary fixtures:
    uv run python tests/fixtures/_build_fixtures.py

All hand-authored text fixtures (sample_chat_*.txt, sample_note.md) are
committed directly and NOT generated by this script.  Only the binary
fixtures (PDF + zip) are generated here.

See 02-PLAN.md Task 2 and 02-RESEARCH.md lines 803-825 for spec.
"""
from __future__ import annotations

import io
import zipfile
from pathlib import Path

FIXTURES_DIR = Path(__file__).parent


def _make_toc_pdf(path: Path) -> None:
    """2-page PDF with bookmarks so doc.get_toc() returns non-empty list."""
    import fitz  # PyMuPDF

    doc = fitz.open()
    for i in range(2):
        page = doc.new_page()
        page.insert_text(
            (50, 72),
            f"Chapter {i + 1}: Test Content\n\nBody text here on page {i + 1}.",
            fontsize=12,
        )
    # set_toc expects [[level, title, page_1based], ...]
    doc.set_toc([[1, "Chapter 1", 1], [1, "Chapter 2", 2]])
    doc.save(str(path))
    doc.close()


def _make_notoc_pdf(path: Path) -> None:
    """2-page PDF with NO bookmarks but with visibly larger heading spans.

    Page 1: large heading (fontsize ~18) + body (fontsize ~10).
    Page 2: similar structure with a different section name.
    The font-size heuristic detects the headings when TOC is absent.
    """
    import fitz  # PyMuPDF

    doc = fitz.open()

    # Page 1: heading at 18pt + body at 10pt
    page1 = doc.new_page()
    page1.insert_text((50, 72), "Cooling System", fontsize=18)
    page1.insert_text(
        (50, 110),
        "The cooling system circulates fresh water and raw water.\n"
        "Inspect the impeller every 200 hours of operation.",
        fontsize=10,
    )

    # Page 2: heading + body
    page2 = doc.new_page()
    page2.insert_text((50, 72), "Electrical System", fontsize=18)
    page2.insert_text(
        (50, 110),
        "The alternator charges the house and start batteries.\n"
        "Check belt tension annually.",
        fontsize=10,
    )

    # NO set_toc call — get_toc() must return []
    doc.save(str(path))
    doc.close()


def _make_scanned_pdf(path: Path) -> None:
    """1-page image-only PDF with no selectable text.

    Inserts a small rendered pixmap rectangle as an image and no text spans,
    so is_image_only() returns True (text < 10 chars + at least one image).
    """
    import fitz  # PyMuPDF

    doc = fitz.open()
    page = doc.new_page()

    # Create a small coloured pixmap to embed as an image.
    # 100x100 RGB pixmap filled with a mid-grey colour.
    pix = fitz.Pixmap(fitz.csRGB, fitz.IRect(0, 0, 100, 100))
    pix.set_rect(pix.irect, (160, 160, 160))  # grey fill

    # Insert the pixmap as an image — no text layer added.
    img_rect = fitz.Rect(50, 50, 300, 300)
    page.insert_image(img_rect, pixmap=pix)

    doc.save(str(path))
    doc.close()


def _make_sample_zip(path: Path, chat_txt_path: Path) -> None:
    """Zip containing only _chat.txt at the root — the normal WhatsApp export shape."""
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(chat_txt_path, arcname="_chat.txt")


def _make_evil_zip(path: Path, chat_txt_path: Path) -> None:
    """Adversarial zip with a benign _chat.txt AND a path-traversal entry.

    The traversal entry uses ZipInfo with an explicit '../../escape.txt' filename
    so the raw bytes of the zip really contain the traversal name.  The safe
    extractor (Wave 3) must reject this entry and only extract _chat.txt.
    """
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # Normal entry
        zf.write(chat_txt_path, arcname="_chat.txt")

        # Adversarial entry: path traversal via ZipInfo
        zi = zipfile.ZipInfo("../../escape.txt")
        zf.writestr(zi, "THIS FILE SHOULD NOT BE EXTRACTED OUTSIDE THE TEMP DIR\n")


def main() -> None:
    """Generate all binary test fixtures into tests/fixtures/.

    PDFs are generated into tests/fixtures/synthetic/ (required by the publish
    hygiene allowlist — see scripts/publish_hygiene.sh CHECK 1).
    """
    synthetic_dir = FIXTURES_DIR / "synthetic"
    synthetic_dir.mkdir(exist_ok=True)
    toc_pdf = synthetic_dir / "sample_toc.pdf"
    notoc_pdf = synthetic_dir / "sample_notoc.pdf"
    scanned_pdf = synthetic_dir / "sample_scanned.pdf"
    chat_zip = FIXTURES_DIR / "sample_chat.zip"
    evil_zip = FIXTURES_DIR / "sample_chat_evil.zip"

    # Source text for the normal zip — reuse the Android fixture.
    android_txt = FIXTURES_DIR / "sample_chat_android.txt"

    print(f"Building {toc_pdf.name} …")
    _make_toc_pdf(toc_pdf)

    print(f"Building {notoc_pdf.name} …")
    _make_notoc_pdf(notoc_pdf)

    print(f"Building {scanned_pdf.name} …")
    _make_scanned_pdf(scanned_pdf)

    print(f"Building {chat_zip.name} …")
    _make_sample_zip(chat_zip, android_txt)

    print(f"Building {evil_zip.name} …")
    _make_evil_zip(evil_zip, android_txt)

    print("All binary fixtures written.")


if __name__ == "__main__":
    main()
